### PR TITLE
AutoUpdate TOC whenever document headings changes

### PR DESCRIPTION
**Pull request by mubaidr**
+Added auto-update to the Table of Content when heading/content is changed/added or removed.

uses Mutation observer for changes monitoring for older browsers polling method is optional.

### CODE REVIEW

**Comment by sman591** [comment]
@mubaidr Trying to search while having autoUpdate enabled throws errors (and causes the page to freeze due to the quantity of errors).

I might be mistaken, but glancing at how autoUpdate is intended, it's picking up that the Search feature is modifying the heading, and causing some sort of problem there?

**Comment by mubaidr** [comment]
@sman591 I have implemented a fix for search functionality. Apparantly it was very small task.

**Comment by mrjlynch** [comment]
Can confirm this works. Would be great to get this merged.

**Comment by qknight** [comment]
Is this now merged? I can't find any code in the PR.

**Pull request closed without merging**
